# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.label.setObjectName("label")
        self.tbFunction = QtWidgets.QLineEdit(self.centralwidget)
        self.tbFunction.setGeometry(QtCore.QRect(10, 30, 371, 28))
        self.tbFunction.setObjectName("tbFunction")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(390, 30, 81, 28))
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(10, 120, 84, 28))
        self.btnLoad.setObjectName("btnLoad")
        self.cbVariable = QtWidgets.QComboBox(self.centralwidget)
        self.cbVariable.setGeometry(QtCore.QRect(10, 80, 371, 28))
        self.cbVariable.setObjectName("cbVariable")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.label_2.setObjectName("label_2")
        self.cbPlotParticles = QtWidgets.QCheckBox(self.centralwidget)
        self.cbPlotParticles.setGeometry(QtCore.QRect(290, 120, 181, 26))
        self.cbPlotParticles.setObjectName("cbPlotParticles")
        self.gbCoordinates = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCoordinates.setEnabled(False)
        self.gbCoordinates.setGeometry(QtCore.QRect(10, 170, 461, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbCoordinates.setFont(font)
        self.gbCoordinates.setObjectName("gbCoordinates")
        self.rbPPitch = QtWidgets.QRadioButton(self.gbCoordinates)
        self.rbPPitch.setGeometry(QtCore.QRect(10, 30, 106, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPPitch.setFont(font)
        self.rbPPitch.setChecked(False)
        self.rbPPitch.setObjectName("rbPPitch")
        self.rbPparPperp = QtWidgets.QRadioButton(self.gbCoordinates)
        self.rbPparPperp.setGeometry(QtCore.QRect(250, 30, 106, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPparPperp.setFont(font)
        self.rbPparPperp.setChecked(True)
        self.rbPparPperp.setObjectName("rbPparPperp")
        self.gbSWeighting = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSWeighting.setEnabled(False)
        self.gbSWeighting.setGeometry(QtCore.QRect(10, 250, 461, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbSWeighting.setFont(font)
        self.gbSWeighting.setObjectName("gbSWeighting")
        self.tbLambda2 = QtWidgets.QLineEdit(self.gbSWeighting)
        self.tbLambda2.setGeometry(QtCore.QRect(180, 30, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbLambda2.setFont(font)
        self.tbLambda2.setObjectName("tbLambda2")
        self.cbLambda2Unit = QtWidgets.QComboBox(self.gbSWeighting)
        self.cbLambda2Unit.setGeometry(QtCore.QRect(240, 30, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbLambda2Unit.setFont(font)
        self.cbLambda2Unit.setObjectName("cbLambda2Unit")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.label_5 = QtWidgets.QLabel(self.gbSWeighting)
        self.label_5.setGeometry(QtCore.QRect(150, 30, 21, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cbLambda1Unit = QtWidgets.QComboBox(self.gbSWeighting)
        self.cbLambda1Unit.setGeometry(QtCore.QRect(80, 30, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbLambda1Unit.setFont(font)
        self.cbLambda1Unit.setObjectName("cbLambda1Unit")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.tbLambda1 = QtWidgets.QLineEdit(self.gbSWeighting)
        self.tbLambda1.setGeometry(QtCore.QRect(20, 30, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbLambda1.setFont(font)
        self.tbLambda1.setObjectName("tbLambda1")
        self.rbFullSpectrum = QtWidgets.QRadioButton(self.gbSWeighting)
        self.rbFullSpectrum.setGeometry(QtCore.QRect(20, 70, 191, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFullSpectrum.setFont(font)
        self.rbFullSpectrum.setChecked(True)
        self.rbFullSpectrum.setObjectName("rbFullSpectrum")
        self.rbPperpVisible = QtWidgets.QRadioButton(self.gbSWeighting)
        self.rbPperpVisible.setGeometry(QtCore.QRect(20, 100, 191, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPperpVisible.setFont(font)
        self.rbPperpVisible.setObjectName("rbPperpVisible")
        self.btnComputeW = QtWidgets.QPushButton(self.gbSWeighting)
        self.btnComputeW.setGeometry(QtCore.QRect(370, 130, 84, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnComputeW.setFont(font)
        self.btnComputeW.setObjectName("btnComputeW")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 420, 84, 28))
        self.pushButton.setObjectName("pushButton")
        self.gbCoordinates.raise_()
        self.gbSWeighting.raise_()
        self.label.raise_()
        self.tbFunction.raise_()
        self.btnBrowse.raise_()
        self.btnLoad.raise_()
        self.cbVariable.raise_()
        self.label_2.raise_()
        self.cbPlotParticles.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cbLambda2Unit.setCurrentIndex(1)
        self.cbLambda1Unit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFT Distribution"))
        self.label.setText(_translate("MainWindow", "Distribution function:"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse..."))
        self.btnLoad.setText(_translate("MainWindow", "Load"))
        self.label_2.setText(_translate("MainWindow", "CODE struct variable:"))
        self.cbPlotParticles.setText(_translate("MainWindow", "Plot number of particles"))
        self.gbCoordinates.setTitle(_translate("MainWindow", "Coordinates"))
        self.rbPPitch.setText(_translate("MainWindow", "p / pitch"))
        self.rbPparPperp.setText(_translate("MainWindow", "ppar / pperp"))
        self.gbSWeighting.setTitle(_translate("MainWindow", "Spectrum weighting"))
        self.tbLambda2.setText(_translate("MainWindow", "800"))
        self.cbLambda2Unit.setCurrentText(_translate("MainWindow", "nm"))
        self.cbLambda2Unit.setItemText(0, _translate("MainWindow", "pm"))
        self.cbLambda2Unit.setItemText(1, _translate("MainWindow", "nm"))
        self.cbLambda2Unit.setItemText(2, _translate("MainWindow", "µm"))
        self.cbLambda2Unit.setItemText(3, _translate("MainWindow", "mm"))
        self.cbLambda2Unit.setItemText(4, _translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "to"))
        self.cbLambda1Unit.setCurrentText(_translate("MainWindow", "nm"))
        self.cbLambda1Unit.setItemText(0, _translate("MainWindow", "pm"))
        self.cbLambda1Unit.setItemText(1, _translate("MainWindow", "nm"))
        self.cbLambda1Unit.setItemText(2, _translate("MainWindow", "µm"))
        self.cbLambda1Unit.setItemText(3, _translate("MainWindow", "mm"))
        self.cbLambda1Unit.setItemText(4, _translate("MainWindow", "m"))
        self.tbLambda1.setText(_translate("MainWindow", "400"))
        self.rbFullSpectrum.setText(_translate("MainWindow", "Full spectrum weighting"))
        self.rbPperpVisible.setText(_translate("MainWindow", "pperp weighting"))
        self.btnComputeW.setText(_translate("MainWindow", "Compute"))
        self.pushButton.setText(_translate("MainWindow", "Export..."))

