# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.label.setObjectName("label")
        self.tbFunction = QtWidgets.QLineEdit(self.centralwidget)
        self.tbFunction.setGeometry(QtCore.QRect(10, 30, 371, 28))
        self.tbFunction.setObjectName("tbFunction")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(390, 30, 81, 28))
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setEnabled(False)
        self.btnLoad.setGeometry(QtCore.QRect(10, 120, 84, 28))
        self.btnLoad.setObjectName("btnLoad")
        self.cbVariable = QtWidgets.QComboBox(self.centralwidget)
        self.cbVariable.setGeometry(QtCore.QRect(10, 80, 371, 28))
        self.cbVariable.setObjectName("cbVariable")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.label_2.setObjectName("label_2")
        self.cbPlotParticles = QtWidgets.QCheckBox(self.centralwidget)
        self.cbPlotParticles.setEnabled(False)
        self.cbPlotParticles.setGeometry(QtCore.QRect(290, 120, 181, 26))
        self.cbPlotParticles.setObjectName("cbPlotParticles")
        self.gbCoordinates = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCoordinates.setEnabled(False)
        self.gbCoordinates.setGeometry(QtCore.QRect(10, 240, 461, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbCoordinates.setFont(font)
        self.gbCoordinates.setObjectName("gbCoordinates")
        self.rbPPitch = QtWidgets.QRadioButton(self.gbCoordinates)
        self.rbPPitch.setGeometry(QtCore.QRect(10, 30, 106, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPPitch.setFont(font)
        self.rbPPitch.setChecked(False)
        self.rbPPitch.setObjectName("rbPPitch")
        self.rbPparPperp = QtWidgets.QRadioButton(self.gbCoordinates)
        self.rbPparPperp.setGeometry(QtCore.QRect(250, 30, 106, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPparPperp.setFont(font)
        self.rbPparPperp.setChecked(True)
        self.rbPparPperp.setObjectName("rbPparPperp")
        self.hsParam1 = QtWidgets.QSlider(self.gbCoordinates)
        self.hsParam1.setGeometry(QtCore.QRect(10, 80, 441, 21))
        self.hsParam1.setMinimum(1)
        self.hsParam1.setMaximum(100)
        self.hsParam1.setProperty("value", 100)
        self.hsParam1.setOrientation(QtCore.Qt.Horizontal)
        self.hsParam1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsParam1.setTickInterval(10)
        self.hsParam1.setObjectName("hsParam1")
        self.lblHsParam1 = QtWidgets.QLabel(self.gbCoordinates)
        self.lblHsParam1.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblHsParam1.setFont(font)
        self.lblHsParam1.setObjectName("lblHsParam1")
        self.lblHsParam2 = QtWidgets.QLabel(self.gbCoordinates)
        self.lblHsParam2.setGeometry(QtCore.QRect(10, 110, 171, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblHsParam2.setFont(font)
        self.lblHsParam2.setObjectName("lblHsParam2")
        self.hsParam2 = QtWidgets.QSlider(self.gbCoordinates)
        self.hsParam2.setGeometry(QtCore.QRect(10, 130, 441, 21))
        self.hsParam2.setMinimum(1)
        self.hsParam2.setMaximum(100)
        self.hsParam2.setProperty("value", 100)
        self.hsParam2.setOrientation(QtCore.Qt.Horizontal)
        self.hsParam2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsParam2.setTickInterval(10)
        self.hsParam2.setObjectName("hsParam2")
        self.lblMaxParam1 = QtWidgets.QLabel(self.gbCoordinates)
        self.lblMaxParam1.setGeometry(QtCore.QRect(270, 60, 181, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblMaxParam1.setFont(font)
        self.lblMaxParam1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMaxParam1.setObjectName("lblMaxParam1")
        self.lblMaxParam2 = QtWidgets.QLabel(self.gbCoordinates)
        self.lblMaxParam2.setGeometry(QtCore.QRect(270, 110, 181, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblMaxParam2.setFont(font)
        self.lblMaxParam2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMaxParam2.setObjectName("lblMaxParam2")
        self.gbSWeighting = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSWeighting.setEnabled(False)
        self.gbSWeighting.setGeometry(QtCore.QRect(10, 410, 461, 191))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbSWeighting.setFont(font)
        self.gbSWeighting.setObjectName("gbSWeighting")
        self.tbLambda2 = QtWidgets.QLineEdit(self.gbSWeighting)
        self.tbLambda2.setGeometry(QtCore.QRect(160, 70, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbLambda2.setFont(font)
        self.tbLambda2.setObjectName("tbLambda2")
        self.cbLambda2Unit = QtWidgets.QComboBox(self.gbSWeighting)
        self.cbLambda2Unit.setGeometry(QtCore.QRect(220, 70, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbLambda2Unit.setFont(font)
        self.cbLambda2Unit.setObjectName("cbLambda2Unit")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.cbLambda2Unit.addItem("")
        self.label_5 = QtWidgets.QLabel(self.gbSWeighting)
        self.label_5.setGeometry(QtCore.QRect(140, 70, 21, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cbLambda1Unit = QtWidgets.QComboBox(self.gbSWeighting)
        self.cbLambda1Unit.setGeometry(QtCore.QRect(80, 70, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbLambda1Unit.setFont(font)
        self.cbLambda1Unit.setObjectName("cbLambda1Unit")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.cbLambda1Unit.addItem("")
        self.tbLambda1 = QtWidgets.QLineEdit(self.gbSWeighting)
        self.tbLambda1.setGeometry(QtCore.QRect(20, 70, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbLambda1.setFont(font)
        self.tbLambda1.setObjectName("tbLambda1")
        self.rbFullSpectrum = QtWidgets.QRadioButton(self.gbSWeighting)
        self.rbFullSpectrum.setGeometry(QtCore.QRect(20, 100, 201, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFullSpectrum.setFont(font)
        self.rbFullSpectrum.setChecked(True)
        self.rbFullSpectrum.setObjectName("rbFullSpectrum")
        self.rbPperpVisible = QtWidgets.QRadioButton(self.gbSWeighting)
        self.rbPperpVisible.setGeometry(QtCore.QRect(20, 130, 191, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPperpVisible.setFont(font)
        self.rbPperpVisible.setObjectName("rbPperpVisible")
        self.btnComputeW = QtWidgets.QPushButton(self.gbSWeighting)
        self.btnComputeW.setGeometry(QtCore.QRect(370, 160, 84, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnComputeW.setFont(font)
        self.btnComputeW.setObjectName("btnComputeW")
        self.label_3 = QtWidgets.QLabel(self.gbSWeighting)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 101, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tbMagField = QtWidgets.QLineEdit(self.gbSWeighting)
        self.tbMagField.setGeometry(QtCore.QRect(380, 70, 51, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbMagField.setFont(font)
        self.tbMagField.setObjectName("tbMagField")
        self.label_4 = QtWidgets.QLabel(self.gbSWeighting)
        self.label_4.setGeometry(QtCore.QRect(440, 70, 16, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnDominate = QtWidgets.QPushButton(self.gbSWeighting)
        self.btnDominate.setGeometry(QtCore.QRect(10, 160, 151, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnDominate.setFont(font)
        self.btnDominate.setObjectName("btnDominate")
        self.btnRecompute = QtWidgets.QPushButton(self.gbSWeighting)
        self.btnRecompute.setGeometry(QtCore.QRect(370, 30, 84, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnRecompute.setFont(font)
        self.btnRecompute.setObjectName("btnRecompute")
        self.cbPresets = QtWidgets.QComboBox(self.gbSWeighting)
        self.cbPresets.setGeometry(QtCore.QRect(20, 30, 191, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbPresets.setFont(font)
        self.cbPresets.setObjectName("cbPresets")
        self.rbBremsstrahlung = QtWidgets.QRadioButton(self.gbSWeighting)
        self.rbBremsstrahlung.setGeometry(QtCore.QRect(240, 100, 201, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbBremsstrahlung.setFont(font)
        self.rbBremsstrahlung.setObjectName("rbBremsstrahlung")
        self.btnExport = QtWidgets.QPushButton(self.centralwidget)
        self.btnExport.setEnabled(False)
        self.btnExport.setGeometry(QtCore.QRect(10, 610, 84, 28))
        self.btnExport.setObjectName("btnExport")
        self.cbNormalizedUnits = QtWidgets.QCheckBox(self.centralwidget)
        self.cbNormalizedUnits.setEnabled(False)
        self.cbNormalizedUnits.setGeometry(QtCore.QRect(290, 150, 181, 26))
        self.cbNormalizedUnits.setChecked(True)
        self.cbNormalizedUnits.setObjectName("cbNormalizedUnits")
        self.cbLogarithmic = QtWidgets.QCheckBox(self.centralwidget)
        self.cbLogarithmic.setEnabled(False)
        self.cbLogarithmic.setGeometry(QtCore.QRect(130, 120, 131, 26))
        self.cbLogarithmic.setChecked(True)
        self.cbLogarithmic.setObjectName("cbLogarithmic")
        self.btnShowPlot = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowPlot.setEnabled(False)
        self.btnShowPlot.setGeometry(QtCore.QRect(10, 150, 84, 28))
        self.btnShowPlot.setObjectName("btnShowPlot")
        self.hsThreshold = QtWidgets.QSlider(self.centralwidget)
        self.hsThreshold.setEnabled(False)
        self.hsThreshold.setGeometry(QtCore.QRect(10, 210, 461, 21))
        self.hsThreshold.setMinimum(0)
        self.hsThreshold.setMaximum(100)
        self.hsThreshold.setProperty("value", 10)
        self.hsThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hsThreshold.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsThreshold.setTickInterval(10)
        self.hsThreshold.setObjectName("hsThreshold")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 81, 20))
        self.label_6.setObjectName("label_6")
        self.lblThreshold = QtWidgets.QLabel(self.centralwidget)
        self.lblThreshold.setEnabled(False)
        self.lblThreshold.setGeometry(QtCore.QRect(300, 190, 171, 20))
        self.lblThreshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblThreshold.setObjectName("lblThreshold")
        self.btnOptimize = QtWidgets.QPushButton(self.centralwidget)
        self.btnOptimize.setEnabled(False)
        self.btnOptimize.setGeometry(QtCore.QRect(100, 610, 121, 28))
        self.btnOptimize.setObjectName("btnOptimize")
        self.cbTime = QtWidgets.QComboBox(self.centralwidget)
        self.cbTime.setEnabled(False)
        self.cbTime.setGeometry(QtCore.QRect(390, 80, 81, 28))
        self.cbTime.setObjectName("cbTime")
        self.cbTime.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(390, 60, 71, 20))
        self.label_7.setObjectName("label_7")
        self.gbCoordinates.raise_()
        self.gbSWeighting.raise_()
        self.label.raise_()
        self.tbFunction.raise_()
        self.btnBrowse.raise_()
        self.btnLoad.raise_()
        self.cbVariable.raise_()
        self.label_2.raise_()
        self.cbPlotParticles.raise_()
        self.btnExport.raise_()
        self.cbNormalizedUnits.raise_()
        self.cbLogarithmic.raise_()
        self.btnShowPlot.raise_()
        self.hsThreshold.raise_()
        self.label_6.raise_()
        self.lblThreshold.raise_()
        self.btnOptimize.raise_()
        self.cbTime.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cbLambda2Unit.setCurrentIndex(1)
        self.cbLambda1Unit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFT Distribution"))
        self.label.setText(_translate("MainWindow", "Distribution function:"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse..."))
        self.btnLoad.setText(_translate("MainWindow", "Load"))
        self.label_2.setText(_translate("MainWindow", "CODE struct variable:"))
        self.cbPlotParticles.setText(_translate("MainWindow", "Plot number of particles"))
        self.gbCoordinates.setTitle(_translate("MainWindow", "Coordinates"))
        self.rbPPitch.setText(_translate("MainWindow", "p / pitch"))
        self.rbPparPperp.setText(_translate("MainWindow", "ppar / pperp"))
        self.lblHsParam1.setText(_translate("MainWindow", "Maximum ppar"))
        self.lblHsParam2.setText(_translate("MainWindow", "Maximum pperp"))
        self.lblMaxParam1.setText(_translate("MainWindow", "∞"))
        self.lblMaxParam2.setText(_translate("MainWindow", "∞"))
        self.gbSWeighting.setTitle(_translate("MainWindow", "Spectrum weighting"))
        self.tbLambda2.setText(_translate("MainWindow", "800"))
        self.cbLambda2Unit.setCurrentText(_translate("MainWindow", "nm"))
        self.cbLambda2Unit.setItemText(0, _translate("MainWindow", "pm"))
        self.cbLambda2Unit.setItemText(1, _translate("MainWindow", "nm"))
        self.cbLambda2Unit.setItemText(2, _translate("MainWindow", "µm"))
        self.cbLambda2Unit.setItemText(3, _translate("MainWindow", "mm"))
        self.cbLambda2Unit.setItemText(4, _translate("MainWindow", "m"))
        self.cbLambda2Unit.setItemText(5, _translate("MainWindow", "mc^2"))
        self.label_5.setText(_translate("MainWindow", "to"))
        self.cbLambda1Unit.setCurrentText(_translate("MainWindow", "nm"))
        self.cbLambda1Unit.setItemText(0, _translate("MainWindow", "pm"))
        self.cbLambda1Unit.setItemText(1, _translate("MainWindow", "nm"))
        self.cbLambda1Unit.setItemText(2, _translate("MainWindow", "µm"))
        self.cbLambda1Unit.setItemText(3, _translate("MainWindow", "mm"))
        self.cbLambda1Unit.setItemText(4, _translate("MainWindow", "m"))
        self.cbLambda1Unit.setItemText(5, _translate("MainWindow", "mc^2"))
        self.tbLambda1.setText(_translate("MainWindow", "400"))
        self.rbFullSpectrum.setText(_translate("MainWindow", "Full synchrotron weighting"))
        self.rbPperpVisible.setText(_translate("MainWindow", "pperp-squared weighting"))
        self.btnComputeW.setText(_translate("MainWindow", "Show"))
        self.label_3.setText(_translate("MainWindow", "Magnetic field:"))
        self.tbMagField.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "T"))
        self.btnDominate.setText(_translate("MainWindow", "Find dominant"))
        self.btnRecompute.setText(_translate("MainWindow", "Compute"))
        self.rbBremsstrahlung.setText(_translate("MainWindow", "Bremsstrahlung weighting"))
        self.btnExport.setText(_translate("MainWindow", "Export..."))
        self.cbNormalizedUnits.setText(_translate("MainWindow", "Normalized units"))
        self.cbLogarithmic.setText(_translate("MainWindow", "Logarithmic plot"))
        self.btnShowPlot.setText(_translate("MainWindow", "Show"))
        self.label_6.setText(_translate("MainWindow", "Threshold:"))
        self.lblThreshold.setText(_translate("MainWindow", "-2.0"))
        self.btnOptimize.setText(_translate("MainWindow", "Optimize grid..."))
        self.cbTime.setCurrentText(_translate("MainWindow", "N/A"))
        self.cbTime.setItemText(0, _translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "Time slice:"))

